# NodeOps Deployment Configuration
# AI-Backed Community Legal Aid Assistant

apiVersion: v1
kind: ConfigMap
metadata:
  name: legal-aid-config
data:
  # Application Configuration
  APP_NAME: "AI-Backed Community Legal Aid Assistant"
  APP_VERSION: "1.0.0"
  DEBUG: "false"
  
  # Database Configuration
  DATABASE_URL: "sqlite:///./legal_aid.db"
  
  # LLM Configuration
  OPENAI_MODEL: "gpt-3.5-turbo"
  OPENAI_MAX_TOKENS: "1000"
  OPENAI_TEMPERATURE: "0.7"
  USE_LOCAL_LLM: "false"
  
  # Security Configuration
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  
  # Rate Limiting
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "3600"
  
  # Legal Resources
  DEFAULT_JURISDICTION: "US"
  ENABLE_RESOURCE_LOOKUP: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: legal-aid-secrets
type: Opaque
stringData:
  # IMPORTANT: Replace these with actual values before deployment
  OPENAI_API_KEY: "your-openai-api-key-here"
  SECRET_KEY: "your-secret-key-change-in-production"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-aid-backend
  labels:
    app: legal-aid-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: legal-aid-backend
  template:
    metadata:
      labels:
        app: legal-aid-backend
    spec:
      containers:
      - name: backend
        image: legal-aid-backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: legal-aid-config
        - secretRef:
            name: legal-aid-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: documents-storage
          mountPath: /app/generated_documents
      volumes:
      - name: documents-storage
        persistentVolumeClaim:
          claimName: legal-aid-documents-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-aid-frontend
  labels:
    app: legal-aid-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: legal-aid-frontend
  template:
    metadata:
      labels:
        app: legal-aid-frontend
    spec:
      containers:
      - name: frontend
        image: legal-aid-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: legal-aid-backend-service
spec:
  selector:
    app: legal-aid-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: legal-aid-frontend-service
spec:
  selector:
    app: legal-aid-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: legal-aid-documents-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legal-aid-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - your-domain.com
    secretName: legal-aid-tls
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: legal-aid-backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: legal-aid-frontend-service
            port:
              number: 80

